blockworks-foundation/mango-ui-v3

- components/Orderbook.tsx
- components/TradePageGrid.tsx
Make orderbook depth change dynamically with adjustments to layout container height
> Dynamic orderbook depth

- components/GroupSize.tsx
- components/Orderbook.tsx
- hooks/useOrderbook.tsx
This PR implements orderbook grouping of 1/5/10/50/100 times the market tickSize via a dropdown in the orderbook panel
> Orderbook grouping

- README.md
> add v3 to read-me

- components/MarketPosition.tsx
- components/PerpPositionsTable.tsx
- components/PerpSideBadge.tsx
- components/PnlText.tsx
- hooks/usePerpPositions.tsx
- package.json
- yarn.lock
users were confused about the inconsistent pnl display
often not aware that they need to settle
so i changed the perp positions table to include positions that dont have 0 pnl
and display this number instead of the previous number in the pnl column
> display unsettled pnl more dominantly

- components/TopBar.tsx
- pages/account/[[...pubkey]].tsx
Allows you to view any mangoAccount via the accounts page.
Access them using: /account/[PUBKEY]
> View anyone's mangoAccount 

- components/AccountInfo.tsx
- components/TradePageGrid.tsx
- yarn.lock
* Add liquidation price for a single asset to the AccountInfo box, increase AccountInfo height
> Add simple liquidation price to AccountInfo

- public/assets/icons/mono/msol.svg
- public/assets/icons/msol.svg
- added mSOL svg icon
- added mSOL mono svg icon
... into  public/assets/icons
> mSOL svg icons

- components/trade_form/AdvancedTradeForm.tsx
- components/trade_form/SimpleTradeForm.tsx
- public/locales/en/common.json
@stevesarmiento  puedes traducir lo tooltip al español?
@rjpeterson would a chinese speaking country ever see this warning?
> add tooltip to country-not-allowed block

- components/TradingView/index.tsx
Updated drawlines() on market refresh to flush lines first if present.
> Flush lines on market change

- utils/index.ts
Updated perpContractPrecision to include LUNA perp (precision = 2).
> Add LUNA Perp Contract Precision

- .github/workflows/codeql-scan.yml
- .github/workflows/trivy-scan.yml
Contents of the PR:
1. Addition of action that runs the CodeQL static application security testing tool. This tool identifies security bugs and unsafe coding practices and supports a range of languages. In this case, it's configured to JS/TS
2. Addition of action that runs Trivy in repository mode. This tools scans dependencies in the software composition and reports on any vulnerable dependencies with fixes available. If a critical vulnerability with fix is found - the job fails. For lower severities, it warns (this can be tweaked).
Both CodeQL and Trivy logs security issues in the GitHub security tab where the team can get context related to an issue and decide course of action with audit trail.
> Automated security scanning features

- components/trade_form/AdvancedTradeForm.tsx
Updated reduceOnly checkbox functionality so that when the reduceOnly checkbox is active, it uses "percentage x basePosition" instead of "percentage x max" which is only appropriate when reduceOnly is inactive.
> Fix reduceOnly checkbox functionality

- components/Button.tsx
- components/ConnectWalletButton.tsx
- components/WalletSelect.tsx
- components/trade_form/AdvancedTradeForm.tsx
- styles/index.css
- tailwind.config.js
Brightened backgrounds of primary buttons. Dimmed connect wallet
> Button styles

- next.config.js
- package.json
- yarn.lock
- Adds [@next/bundle-analyzer](https://www.npmjs.com/package/@next/bundle-analyzer) so we can inspect server and client builds
- Run the tool with `yarn analyze`
> Adds yarn analyze

- package.json
- yarn.lock
- Moves `@next/bundle-analyzer` to devDependencies
> Moves @next/bundle-analyzer to devDependencies

- components/trade_form/AdvancedTradeForm.tsx
- Updates advanced trade form to only show `Post & Slide` checkbox if the order type is limit.
> Shows post and slide only on limit

- components/TradeHistoryTable.tsx
- pages/account.tsx
Changes the layout of mango rewards, more and filter buttons on mobile and sm breakpoint
> fix button positions on mobile

- components/TradingView/index.tsx
- styles/index.css
As requested by TradingView...
> add tradingview chart attribution link

- components/CloseAccountModal.tsx
Deletes alerts as part of close account func
> delete active alerts when closing account

- components/CreateAlertModal.tsx
- components/TradeNavMenu.tsx
Favorite button is broken and favorites menu isn't updating like it should.
> fix remove from favorites

- components/ShareModal.tsx
- pages/account.tsx
- pages/index.tsx
- public/locales/en/share-modal.json
- public/locales/es/share-modal.json
- public/locales/es/tv-chart.json
- public/locales/zh/share-modal.json
- public/locales/zh/tv-chart.json
- public/locales/zh_tw/share-modal.json
- public/locales/zh_tw/tv-chart.json
This PR adds localization tags and Chinese translations for the new ShareModal. It also replaces several non-standard "space" characters in locale files with standard ones.
> Translate ShareModal

- components/WithdrawModal.tsx
- package.json
- yarn.lock
> upgrade mango client

- @types/types.tsx
- package.json
- stores/useMangoStore.tsx
- utils/getParsedNftAccountsByOwner.ts
- utils/index.ts
- utils/metaplex.ts
- yarn.lock
> move fns from @nfteyez/sol-rayz into app

- package.json
- yarn.lock
> upgrade mango-client to 3.4.8

- components/NftProfilePicModal.tsx
- public/locales/en/profile.json
- public/locales/es/profile.json
- public/locales/zh/profile.json
- public/locales/zh_tw/profile.json
> add nft modal empty state

- components/AccountsModal.tsx
> show health instead of leverage

- components/IntroTips.tsx
- components/NewAccount.tsx
- components/TopBar.tsx
- pages/index.tsx
- public/locales/en/common.json
Show create account modal after intro tips and get started button. Show button in topbar when a user has no accounts
> improve no account flow

- components/mobile/MobileTradePage.tsx
- components/mobile/SwipeableTabs.tsx
- hooks/useDrag.tsx
- package.json
- pages/account.tsx
- pages/markets.tsx
- pages/stats.tsx
- styles/index.css
- yarn.lock
Improve tabs on mobile so we don't have to switch out to a dropdown when there are too many items
> scrolling mobile tabs

- components/MarketPosition.tsx
- components/PerpPositions/RedeemDropdown.tsx
where you don't have to sit and wait for each transaction to go through and confirm;
still has bug with Redeem All where the spinner doesn't stop. @tjshipe do you know how to resolve that?
> Make Redeem All and Redeem Positive have correct behavior 

- components/AccountInfo.tsx
> updated health doc url

- components/CloseAccountModal.tsx
- public/locales/en/close-account.json
- public/locales/es/close-account.json
- public/locales/zh/close-account.json
- public/locales/zh_tw/close-account.json
Currently, you can't close an account with unsettled balances. This pr adds text to inform users to settle balances before closing an account.
> add unsettled balances to close account

- components/OpenOrdersTable.tsx
- package.json
- yarn.lock
- Added spot market to the existing perps market
- Will be same as original PR
> Extending cancel all to spot market too.

- components/Layout.tsx
- components/TradePageGrid.tsx
To better accommodate small desktop/laptops
> add additional breakpoint to trade page grid

- components/JupiterForm.tsx
- components/SwapTokenSelect.tsx
and adds tokens in wallet to the top of the token list for "Pay" input
> add popular tokens to swap token select

- package.json
- yarn.lock
> Upgrade mango-client to remove LUNA-PERP from devnet.2 IDS

- pages/referral.tsx
- public/locales/en/referrals.json
- public/locales/es/referrals.json
Was a bit broken with the new nav
> Fix referral layout

- components/stats_page/StatsTotals.tsx
> fix undefined error

- components/AccountsModal.tsx
- components/Layout.tsx
- pages/borrow.tsx
- pages/fees.tsx
- pages/index.tsx
- pages/leaderboard.tsx
- pages/markets.tsx
- pages/referral.tsx
- pages/risk-calculator.tsx
- pages/stats.tsx
- pages/swap.tsx
Adds delegated account icon/tooltip to account label in top bar.
> add delegated account icon label

- components/AccountOverviewPopover.tsx
- components/SideNav.tsx
Health wasn't being passed to the health heart in side nav.
> pass health to account summary

- components/LeaderboardTable.tsx
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/zh/common.json
- public/locales/zh_tw/common.json
> add spot pnl to leaderboard

- components/AccountOverviewPopover.tsx
- components/BalancesTable.tsx
- components/Button.tsx
- components/Layout.tsx
A few miscellaneous styling fixes.
> fix styling bugs

- components/WithdrawModal.tsx
- components/trade_form/AdvancedTradeForm.tsx
- hooks/useHydrateStore.tsx
- package.json
- stores/useMangoStore.tsx
- yarn.lock
> Prepare UI for market delisting

- components/account_page/AccountHistory.tsx
- components/account_page/AccountInterest.tsx
- hooks/useTradeHistory.tsx
- pages/risk-calculator.tsx
- utils/index.ts
> Hardcode required info for delisted markets

- components/account_page/AccountOverview.tsx
- components/account_page/AccountOverviewStats.tsx
> fix broken health docs link and chart range

- components/HealthHeart.tsx
Had a mistake in the condition
> fix health heart animation

- package.json
- pages/_app.tsx
- yarn.lock
Add support for Coinbase Wallet.
> Add Coinbase Wallet support

- components/ConnectWalletButton.tsx
- components/LeaderboardTable.tsx
- components/NftProfilePicModal.tsx
- components/ProfileImage.tsx
- components/ProfileImageButton.tsx
- components/WalletAdapter/WalletListener.tsx
- package.json
- pages/account.tsx
- pages/profile.tsx
- stores/useMangoStore.tsx
- yarn.lock
Makes loading and saving nft profile pics faster.
** this beaks existing profile pics so anyone who has one will need to redo **
> save profile images to our db

- components/CloseAccountModal.tsx
Fix close account TX size by disabling fee prioritization
> Fix close account TX size by disabling fee prioritization

- components/PerpPositionsTable.tsx
- public/locales/en/common.json
- public/locales/es/common.json
- public/locales/kr/common.json
- public/locales/ru/common.json
- public/locales/zh/common.json
- public/locales/zh_tw/common.json
To perp table. If we can merge this first I'll update the existing pr for the balances table
> add liq price tooltip

- package.json
- pages/_app.tsx
- yarn.lock
Performance issues with the previous PR (https://github.com/blockworks-foundation/mango-ui-v3/pull/395) are fixed in @solana/wallet-adapter-wallets 0.18.2, re-adding the Coinbase adapter as before
> Re-add Coinbase Wallet Adapter

- pages/_app.tsx
> WalletConnect adapter integration

- hooks/useFees.tsx
Fix taker fee display on fees page
> Fix fees page

- components/TVChartContainer.tsx
fix bug where all but most recent trade execution disappears on order fill
> tradingview chart bug fix

- components/account_page/AccountOverviewStats.tsx
Long Exposure => Assets
Short Exposure => Liabilities
> edit exposure chart title copy

- .github/workflows/codeql-scan.yml
- .github/workflows/node.js.yml
- .github/workflows/trivy-scan.yml
- .husky/pre-commit
- hooks/useFees.tsx
- pages/fees.tsx
- stores/useMangoStore.tsx
- Run prettier
- Enable CI workflows for PRs to production branch
- Add prettier to husky pre-commit hook
> Run prettier on production branch and pre-commit
