blockworks-foundation/mango-ui-v3

@types/types.tsx, components/BalancesTable.tsx, components/TableElements.tsx, components/TopBar.tsx, components/TradeHistoryTable.tsx, components/TradePageGrid.tsx, components/UserInfo.tsx, components/account-page/AccountHistory.tsx, components/account-page/AccountOverview.tsx, components/mobile/MobileMenu.tsx, components/stats-page/StatsTotals.tsx, hooks/useBalances.tsx, hooks/useViewport.tsx, pages/_app.tsx, pages/account.tsx
Keen to improve all of the tables on mobile. We could do expanding rows with only the most useful info displayed on the row and the rest within the expandable panel.
• Added a hook to conditionally render based on breakpoints – we had been using 'hidden' tailwind class but I find this harder to maintain and less flexible than having a variable.
• Added balance value to what gets returned from useBalances and enabled sorting on the balances table.
=> improve balances table

components/TradingView/index.tsx, fix-husky.js, yarn.lock
Added the ability to visualize orders on the TradingView widget.
Needs to be pulled in conjunction with mango-client-v3/tradingview-order-lines pull request which adds the ability to modify an order (cancel and replace) in a single transaction.
=> Add Tradingview Order Lines

components/BalancesTable.tsx, components/MarketBalances.tsx, components/MarketPosition.tsx, components/PerpPositionsTable.tsx
Added:
• Click balances to populate trade form
• Populate both base and quote
• Only enable on the trade page for the associated asset/market
There's a bit of duplicate code (handleSizeClick). Was thinking about a hook to manage trade form state but a re-factor of the trade form is imminent so have copied the function for now. Let me know if you want this changed.
=> pre-fill spot balance

components/TradeHistoryTable.tsx
Added links to the markets from the trade history table, like in the perp positions tab. Like in the perp positions tab, the market is not linked if already on the page.
=> Link to markets from trade history table

components/OpenOrdersTable.tsx
Like the other tables, clicking the market will navigate to the page, unless already there. In the screenshot I am already on the BTC-PERP page.
=> Link market from desktop open orders table

components/trade_form/AdvancedTradeForm.tsx, components/trade_form/SimpleTradeForm.tsx
Displays a warning under and disables the trade button when a user doesn't have enough SOL in the wallet to cover the transaction cost
=> disable trade button and show warning when user has no SOL

utils/wallet-adapters/solflare-extension.ts
Some legacy clients have only the toString method supported so this is the fix to make the adapter backwards compatible
=> backwards compatibility to pubkey object

components/JupiterForm.tsx, components/icons.tsx
• Mostly styling updates
• Show wallet balances in a side draw and populate form onClick. 
• Modal for first-time swap to explain wallet vs mango account. Thinking users should only need to see this once so we can remove the text currently in the UI. Might need to monitor feedback.
=> Swap styling

components/ManualRefresh.tsx, components/MarketDetails.tsx
We have a tip for the manual refresh button but it is hidden if the user has no account (likely if they are going through the intro tour).
PR changes it to show even with no account but only update the account functions if the user has an account.
=> show refresh button when no account

utils/index.ts
UI precision information doesn't currently include MSOL, BNB, or AVAX.
=> Update Precision Utils Information

components/SettingsModal.tsx, components/trade_form/AdvancedTradeForm.tsx, public/locales/en/common.json
pro: prevent users from accidentally shorting when closing longs, potentially incurring high losses, especially if short runs for a while
contra: one click more for most users
=> disable spot margin by default

components/OpenOrdersTable.tsx
Hi team, just found a tiny typo. It should be `side` instead of `size`:
=> fix typo in orders table

components/AccountsModal.tsx, components/CreateAlertModal.tsx, components/TradeHistoryTable.tsx, styles/index.css
Currently the UI has some awkward line breaking when displaying CJK characters. I've added the keep-break class (not included in default tailwind) to resolve this.
Also cleared up some localization errors caused by the word "New"
=> Add keep-break class to solve issues with CJK display

pages/index.tsx
I accidentally made a typo in the url when trying to redirect to another market and faced this unfriendly error:
My url was: `http://.../?name=ETC-PERP`, this error happens locally and on prod.
I've tracked where the state gets updated and when there is missing data I've suggested to redirect to home, thus forcing to fallback to the default market/pair.
WDYT?
=> Handle input of invalid pairs

components/JupiterForm.tsx
- Fix for `More` dropdown going behind Swap form:
=> Removes z-index on Jupiter form

components/account_page/MangoAccountSearch.tsx, pages/account.tsx
- Adds component `MangoAccountSearch` which adds an input for looking up a mango account address. This component is only visible if the user is not connected.
- Desktop:
- Mobile:
=> Adds MangoAccountSearch to /account

components/account_page/AccountOverview.tsx, components/account_page/AccountPerformance.tsx
I am looking to switch from using flask to fast-api for the api server.
During my testing I found that flask is silently sorting the json response on keys -> so switching to fast-api would reverse the order.
So this change would ensure the correct ordering using both flask and fast-api.
The sorting could be removed after the switch over.
=> sort performance data explicitly

.github/workflows/node.js.yml, components/BalancesTable.tsx
- Fix for Show fewer decimals for large balances: https://trello.com/c/C2XKsREa/114-show-fewer-decimals-for-large-balances
- If the balance is greater than or equal to 1,000,000 show 2 decimals or If the balance is greater than or equal to 1,000 show 3 decimals
- Also displays `0` for floats that are equal to `0`
=> Show fewer decimals for large balances

components/trade_form/AdvancedTradeForm.tsx
- Fix for: The trade button was disabled on page load without a price after selecting `Post & Slide` input
=> Fixes disabledTradeButton if post only slide

components/TopBar.tsx
- Adds a `Devnet` tag in the nav if you're connected to devnet. Nothing appears if on mainnet.
=> Adds devnet tag in nav

components/trade_form/AdvancedTradeForm.tsx, public/locales/es/common.json
- Capitalizes `Portafolio` in Spanish translation
- Hides price placeholder when market type and post only slide is enabled
=> Small QA changes

pages/referral.tsx
– Total referrals was showing the number of referral payments rather than the number of accounts referred.
– The referee address was showing the referrer address in the earnings history table
– Also this endpoint `https://mango-transaction-log.herokuapp.com/v3/stats/referral-fees-total?referrer-account=${pk}` doesn't return anything (for one of my accounts when there is referral history). Have asked Nick about it
=> fix referrals count and referee address

components/Input.tsx
Get this warning locally:
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
Doesn't show up in prod so not sure if this is necessary.
=> fix forwardref warning

public/locales/es/common.json, public/locales/zh/common.json, public/locales/zh_tw/common.json
"tooltip-post-and-slide" was missing in es, zh, zh_tw locales
=> add missing translation key

components/trade_form/AdvancedTradeForm.tsx
Price sometimes had a lot of decimals when switching from market to limit type trades. Now has a max precision of ticksize decimals
Noticed that sometimes the price at the top of the book is different from the price populated for a market order. This is instantly after selecting market. Not sure if this is expected or not.
=> format price on trade type switch

public/locales/en/delegate.json
There was an extra comma  (invalid JSON format) in delegate.json, which prevented React i18next from parsing the locale file.
=> Fixed json format so translation will load 

components/account_page/PerformanceChart.tsx
The account performance chart "value" and "PnL" buttons weren't working properly on the non-English UI. This PR adds the "names" argument as the localized text and retains the English strings as the "values" arg.
=> add "names" arg to account graph buttongroup

components/account_page/AccountPerformancePerToken.tsx, pages/risk-calculator.tsx
- Removed reliance on multiple variables for loading perp positions, notably making the MNGO-PERP fail to load correctly.
- Removed base position from Unsettled Funding calculation as it's displayed in quote token, not the perp token
- Fixed perps In Orders calculation so it was consistent in both places it's present
=> Fix Risk Calculator PERP loading unreliably

components/NewAccount.tsx
Currently, the create account transaction submits and fails if no deposit amount is entered. This validates an amount
=> validate first deposit amount input

components/SwapTokenInsights.tsx
Most of the time the best/worst performing tokens are the ones with almost 0 volume. This makes the minimum 24h volume $10000
=> filter low volume tokens from swap insights

components/trade_form/AdvancedTradeForm.tsx, pages/index.tsx
Size now updates on market change.
Also, added a mechanism for market orders which updates the size of either base or quote depending on which the user keyed in. You can now choose to enter a base or quote amount and that value will stay static when the mark price changes.
=> fix trade form size bugs

components/JupiterForm.tsx, pages/swap.tsx, public/locales/en/swap.json, public/locales/es/swap.json, public/locales/zh/swap.json, public/locales/zh_tw/swap.json
Let users know swaps interact with their connected wallet, not their Mango Account
=> improve swap description

components/AlphaModal.tsx, components/SettingsModal.tsx
Set the NEXT_LOCALE cookie (https://nextjs.org/docs/advanced-features/i18n-routing#leveraging-the-next_locale-cookie) when the user chooses a language, to override locale detection based on the browser language.
=> Override locale detection with user setting

components/Modal.tsx, components/SerumCompModal.tsx, components/SideNav.tsx, pages/index.tsx, pages/win-srm.tsx
Shows a modal on trade page (only shows once)
Adds a page /win-srm with competition info and results
Adds a link to comp page in the "More" menu in side nav
** Content and data queries need to be checked for accuracy. Account PnL query is not finished **
=> add modal and page for spot comp

components/trade_form/AdvancedTradeForm.tsx
Problem: Spot sell - spotMax reflects availableBalance when using the percent buttons and margin unselected
Changes: Spot sell - spotMax reflects depositBalance when using the percent buttons and margin unselected
Image below (left: spotMax before change, right: spotMax after change, bottom: Balance)
In the above balance is 0.043109999, so it rounds to 0.0432 in balance, but 0.0431 is all that's available to sell at the 4 digit step size.
=> Handle margined deposit balances in SpotMax

components/TVChartContainer.tsx, public/locales/en/tv-chart.json, public/locales/es/tv-chart.json, public/locales/kr/tv-chart.json, public/locales/ru/tv-chart.json, public/locales/zh/tv-chart.json, public/locales/zh_tw/tv-chart.json, stores/useMangoStore.tsx
Per [this comment](https://discord.com/channels/791995070613159966/833812133316657183/1013577729003753534) in Discord, I've added FTX style execution arrows to the tradingview chart. It currently draws an arrow for every trade in the current market in the accounts trade history. I have not tested it on an account with hundreds or thousands of trades. Hopefully someone with an account like that can try it out.
=> Add execution arrows to tradingview chart
